name: julias_yt_dlp_ui
description: "Uma interface gráfica feita em Flutter para a ferramenta yt-dlp."
version: 1.3.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  path: ^1.9.0
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  intl: ^0.19.0
  window_manager: ^0.4.3
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.1
  transparent_image: ^2.0.1
  skeletonizer: ^1.4.3
  catppuccin_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/yt-dlp/
